# These are supported sponsorship platforms

github: # Replace with your GitHub Sponsors username or organization, e.g., 'solosoluzioni' or 'opencartitalia'
custom: ["https://www.opencartitalia.it", "https://www.solosoluzioni.it"]
